### ISSUE TITLE
size 命令有问题

### ISSUE THREAD

**Issue by realByg** [donwa/gclone#20]
遇到大文件夹的时候无法计算全，多跑几次返回结果不一样

![image](https://user-images.githubusercontent.com/39550067/80176247-81a45380-862a-11ea-8239-9787c36c86d3.png)

我的配置是

```
[K]
type = drive
scope = drive
service_account_file = /path/to/json
service_account_file_path = /path/
root_folder_id = teamdriveid
```

所有的sa账户都确认已经加到团队盘里面了

**Comment by he-sb** [comment]
遇到了相同问题，`rclone size` 结果是准确的，`gclone size` 大小总有问题，而且每次结果都不同。

**Comment by l396** [comment]
我和黄屁股校长还有傻逼大佬一样遇到这个问题，目前只能用rclone，但rclone写路径又太麻烦。还请gclone大佬抽时间研究一下。谢谢
