### ISSUE TITLE
请问大佬goindex和oneindex的项目为什么删除了

### ISSUE THREAD

**Issue by Vocare123** [donwa/gclone#21]
今天想部署一下goindex，结果打开书签发现网页404了..而且忘记fork了...

**Comment by Mackerly** [comment]
关注后续进展

**Comment by Vocare123** [comment]
> 关注后续进展

OK,大佬加油

**Comment by thegreatestminer** [comment]
这是非常令人担忧的。

**Comment by Masterchiefm** [comment]
是啊，求解决方案，我们可以把js那些东西放自己服务器里

**Comment by fanpest** [comment]
是FORK吗，我之前已保存过，修改INDEX.JS脚本的哪段才能继续使用？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "愿乘风归去"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 上午10:35
收件人: "donwa/gclone"<gclone@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [donwa/gclone] 请问大佬goindex和oneindex的项目为什么删除了 (#21)





 
是啊，求解决方案，我们可以把js那些东西放自己服务器里
 
&mdash;

**Comment by GaryLz** [comment]
解决方案，在这里

[解决goindex作者删库，导致goindex打不开的问题](https://shikey.com/2020/04/27/goindex-index-js-repack.html)

goindex问题应该解决了，请close issues

----

#### 题外话
PanDownload开发者被抓，这所引起的连带效应，可不是人一觉醒来就结束了。
虽然对国内未来几年的开发者环境感到十分担忧，
Donwa大佬，不管怎样，和之前很多前辈一样，在我心中也是“英雄”的分量。Respect!
也希望我哪天也有这样的实力和勇气，带给大家一些好的改变。

**Comment by Vocare123** [comment]
> 解决方案，在这里
> 
> [解决goindex作者删库，导致goindex打不开的问题](https://shikey.com/2020/04/27/goindex-index-js-repack.html)
> 
> goindex问题应该解决了，请close issues
> 
> #### 题外话
> PanDownload开发者被抓，这所引起的连带效应，可不是人一觉醒来就结束了。
> 虽然对国内未来几年的开发者环境感到十分担忧，
> Donwa大佬，不管怎样，和之前很多前辈一样，在我心中也是“英雄”的分量。Respect!
> 也希望我哪天也有这样的实力和勇气，带给大家一些好的改变。

感谢大佬~

**Comment by fanpest** [comment]
不知道为什么，我没改还能用



---原始邮件---
发件人: "Gary Leung"<notifications@github.com&gt;
发送时间: 2020年4月29日(周三) 凌晨0:07
收件人: "donwa/gclone"<gclone@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"fanpest"<28962845@qq.com&gt;;
主题: Re: [donwa/gclone] 请问大佬goindex和oneindex的项目为什么删除了 (#21)




 
解决方案，在这里
 
解决goindex作者删库，导致goindex打不开的问题
 
goindex问题应该解决了，请close issues
 
 
题外话
 
PanDownload开发者被抓，这所引起的连带效应，可不是人一觉醒来就结束了。
 虽然对国内未来几年的开发者环境感到十分担忧，
 Donwa大佬，不管怎样，和之前很多前辈一样，在我心中也是“英雄”的分量。Respect!
 也希望我哪天也有这样的实力和勇气，带给大家一些好的改变。

**Comment by thegreatestminer** [comment]
@fanpest 清除浏览器的缓存并重新尝试
