### ISSUE TITLE
出现dailyLimitExceededUnreg，求帮助

### ISSUE THREAD

**Issue by shjdgwj** [donwa/gclone#30]
![QQ截图20200516144543](https://user-images.githubusercontent.com/11689121/82112899-190d4a00-9784-11ea-9309-00c188771613.jpg)
出现上述报错，打开其中的链接显示如下内容

{"error":{"errors":[{"domain":"usageLimits","reason":"dailyLimitExceededUnreg","message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.","extendedHelp":"https://code.google.com/apis/console"}],"code":403,"message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."}}

请问如何解决？

**Comment by anlo1220** [comment]
service_account_file_path = /root/accounts/  

 /root/accounts need "/" >>>> /root/accounts/
