### ISSUE TITLE
Debian 9/10 无法正常安装gclone

### ISSUE THREAD

**Issue by Leonyan938** [donwa/gclone#4]
作者大大你好   我试图在debian9上安装gclone  显示貌似是安装成功了，但是输入各种命令都会提示错误  入下图   请问此问题能解决吗？

谢谢！
<img width="568" alt="image" src="https://user-images.githubusercontent.com/3710665/74593825-01d09a80-5077-11ea-8d41-e6f18815d5f7.png">

**Comment by donwa** [comment]
你的gclone 被映射到 git clone 去了。

cp /usr/bin/gclone /usr/bin/rclone 吧。直接用rclone 来用。

**Comment by Leonyan938** [comment]
哦哦，多谢！ 我去试试

**Comment by donwa** [comment]
是的，你可以观察是否能超750G。  
如果是server side copy 记得加   --drive-server-side-across-configs。  
本地到云端不要加。

**Comment by Leonyan938** [comment]
非常赞  已经能正常工作啦！
