### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by huyaohuyao** [donwa/gclone#40]
运行给clone之后
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xbd69e3]

goroutine 357 [running]:
github.com/donwa/gclone/backend/drive.(*Fs).list(0xc000308700, 0x1a269c0, 0xc0004ec640, 0xc000617d98, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc000617da8, ...)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:797 +0x1e3
github.com/donwa/gclone/backend/drive.(*Fs).List(0xc000308700, 0x1a269c0, 0xc0004ec640, 0xc000706360, 0x8e, 0x0, 0x0, 0x0, 0xc08278de4b2ec249, 0xcbca736f12208bee)
        /home/runner/work/gclone/gclone/backend/drive/drive.go:1631 +0x1e9
github.com/rclone/rclone/fs/list.DirSorted(0x1a269c0, 0xc0004ec640, 0x1a3dca0, 0xc000308700, 0xb00fae385db0a900, 0xc000706360, 0x8e, 0x938bc8a20e498d34, 0x2e647f646ffda325, 0x42e2ca, ...)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/list/list.go:24 +0x7d
github.com/rclone/rclone/fs/march.(*March).makeListDir.func1(0xc000706360, 0x8e, 0xdbbd9fec2cfa1415, 0xe614f9d5032fff95, 0x9188f04a89dddc88, 0x1fb5d9c7809c6227, 0x4af0ef74802deb30)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/march/march.go:79 +0x68
github.com/rclone/rclone/fs/march.(*March).processJob.func1(0xc000663490, 0xc000469710, 0xc000706360, 0x8e, 0xc000706360, 0x8e, 0x7ffffffb, 0x0, 0x100, 0xc000644160, ...)
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/march/march.go:383 +0x82
created by github.com/rclone/rclone/fs/march.(*March).processJob
        /home/runner/go/pkg/mod/github.com/rclone/rclone@v1.51.0/fs/march/march.go:381 +0x130

**Comment by jason8303** [comment]
我也遇到同样的问题，我是运行的 gclone sync

**Comment by huyaohuyao** [comment]
破案了，conf里面accounts后面少了/
fix it，rclone.conf  account path miss /

**Comment by jason8303** [comment]
可是我在后面加了/ 还是同样的问题，

**Comment by jason8303** [comment]
> 破案了，conf里面accounts后面少了/
> fix it，rclone.conf account path miss /

搞定，结案
