### ISSUE TITLE
关于 service_account_file 这个配置

### ISSUE THREAD

**Issue by ysmintor** [donwa/gclone#6]
> service_account_file = /root/accounts/1.json 

是否在 accounts 下的 json 文件必须是1.json  2.json 3.json 这样啊？不会自动搜索这个目录下的 json 文件吗？ 600个 乱码一样的文件如果是必须为数字就要改名了。

**Comment by bingo235** [comment]
随便把你SA目录下的json挑一个配置上就行

**Comment by ysmintor** [comment]
确实如此，好奇为什么要配置一个，既然者都将目录给配置了，里面的文件也就可以直接找到啊。

**Comment by bingo235** [comment]
不配置也可以
json本质是一个账号的token信息，不配置rclone默认会使用你配置的主账号的client_id token去访问。

**Comment by bingo235** [comment]
理论上只要去rclone配置里加一个最小配置块就可以访问了
```
[gd1]
type = drive
scope = drive
service_account_file =
service_account_file_path = 
```
